<a href="https://colab.research.google.com/github/dragonfly-lab/Story/blob/main/If_sentences_contain_KWs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
!pip install openpyxl

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: openpyxl in /usr/local/lib/python3.8/dist-packages (3.0.10)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.8/dist-packages (from openpyxl) (1.1.0)

In [ ]:
df_page = pd.read_excel("blog.xlsx")

In [ ]:
df_country = pd.read_excel("Countries.xlsx")

In [ ]:
display(df_page)

,Original Url,Status Code,Status,Title 1,H1-1,H2-1,H2-2,Redirect URL
0,https://immigrationlawyers-london.com/blog/set...,200,OK,Can A Tier 2 Migrant Set Up A Limited Company?...,Setting Up A Limited Company As a Tier 2 Visa ...,Can I Set Up A Limited Company While In The UK...,Can My Own Limited Company Sponsor My Stay In ...,NaN
1,https://immigrationlawyers-london.com/blog/bre...,200,OK,Settled & Pre-Settled Status Check - View and ...,"How to Check my Settled Status as an EU, EEA o...",How do I check my Settled Status Progress?,Reiss Edwards Awards,NaN
2,https://immigrationlawyers-london.com/blog/per...,200,OK,Permanent Resident Application and Children | ...,Permanent Resident Application and Children,Permanent Residence And Children,Registering A British Born Child With EEA Citi...,NaN
3,https://immigrationlawyers-london.com/blog/com...,200,OK,Combining Employed and Self-Employed for A Spo...,Combining Employed and Self-Employed for A Spo...,How Much Do You Need To Earn To Apply For A Sp...,Can You Apply For A Spouse Visa If Your Partne...,NaN
4,https://immigrationlawyers-london.com/blog/wor...,200,OK,Tier 2 (Skilled Worker Visa) Work Restrictions,Tier 2 (Skilled Worker) Visa Work Restrictions...,Tier 2 / Skilled Worker visa maximum and minim...,Can a Tier 2 / Skilled Worker visa holder do a...,NaN
...,...,...,...,...,...,...,...,...
685,https://immigrationlawyers-london.com/blog/eng...,200,OK,English Language Requirement for Spouse Visa a...,English Language Requirement for Spouse Visa a...,English language requirements for Spouse visa,English language requirement exemptions for Sp...,NaN
686,https://immigrationlawyers-london.com/blog/glo...,200,OK,Global Talent visa vs Skilled Worker Visa: Key...,Global Talent visa vs Skilled Worker Visa: Key...,Job flexibility,Visa requirements,NaN
687,https://immigrationlawyers-london.com/blog/rec...,200,OK,UK Immigration Rules for Recruiting Social Car...,UK Immigration Rules for Recruiting Social Car...,How to employ a social care worker from abroad,How to apply for a sponsor licence,NaN
688,https://immigrationlawyers-london.com/blog/uk-...,200,OK,UK Civil Partnership Visa Requirements and App...,UK Civil Partnership Visa Requirements and App...,Civil Partnership visa requirements,Document required for civil partnership visa a...,NaN
689,https://immigrationlawyers-london.com/blog/uk-...,200,OK,UK Marriage Visa Requirements and Application,UK Marriage Visa Requirements and Application,What is UK Marriage Visa?,UK Marriage Visa Requirements,NaN

In [ ]:
display(df_country)

        Countries
0       Argentina
1       Australia
2      Australian
3         Austria
4         Belgium
..            ...
65       Thailand
66         Turkey
67            UAE
68  United States
69        Vietnam

[70 rows x 1 columns]

In [ ]:
df_page["Contains keyword"] = ""

In [ ]:
# interate throught row of df_page
for i, row in df_page.iterrows():
  # interate through row of df_country
  for j, country in df_country.iterrows():
    # check if keyword is in the "Title" column of df_pages
    if country['Countries'].lower() in row['Title 1'].lower():
      # add "Yes" to the corresponding cell in df_pages
      df_page.at[i, "Contains keyword"] = "Yes" 
      break
display(df_page)

,Original Url,Status Code,Status,Title 1,H1-1,H2-1,H2-2,Redirect URL,Contains keyword
0,https://immigrationlawyers-london.com/blog/set...,200,OK,Can A Tier 2 Migrant Set Up A Limited Company?...,Setting Up A Limited Company As a Tier 2 Visa ...,Can I Set Up A Limited Company While In The UK...,Can My Own Limited Company Sponsor My Stay In ...,NaN,
1,https://immigrationlawyers-london.com/blog/bre...,200,OK,Settled & Pre-Settled Status Check - View and ...,"How to Check my Settled Status as an EU, EEA o...",How do I check my Settled Status Progress?,Reiss Edwards Awards,NaN,
2,https://immigrationlawyers-london.com/blog/per...,200,OK,Permanent Resident Application and Children | ...,Permanent Resident Application and Children,Permanent Residence And Children,Registering A British Born Child With EEA Citi...,NaN,
3,https://immigrationlawyers-london.com/blog/com...,200,OK,Combining Employed and Self-Employed for A Spo...,Combining Employed and Self-Employed for A Spo...,How Much Do You Need To Earn To Apply For A Sp...,Can You Apply For A Spouse Visa If Your Partne...,NaN,
4,https://immigrationlawyers-london.com/blog/wor...,200,OK,Tier 2 (Skilled Worker Visa) Work Restrictions,Tier 2 (Skilled Worker) Visa Work Restrictions...,Tier 2 / Skilled Worker visa maximum and minim...,Can a Tier 2 / Skilled Worker visa holder do a...,NaN,
...,...,...,...,...,...,...,...,...,...
685,https://immigrationlawyers-london.com/blog/eng...,200,OK,English Language Requirement for Spouse Visa a...,English Language Requirement for Spouse Visa a...,English language requirements for Spouse visa,English language requirement exemptions for Sp...,NaN,
686,https://immigrationlawyers-london.com/blog/glo...,200,OK,Global Talent visa vs Skilled Worker Visa: Key...,Global Talent visa vs Skilled Worker Visa: Key...,Job flexibility,Visa requirements,NaN,
687,https://immigrationlawyers-london.com/blog/rec...,200,OK,UK Immigration Rules for Recruiting Social Car...,UK Immigration Rules for Recruiting Social Car...,How to employ a social care worker from abroad,How to apply for a sponsor licence,NaN,
688,https://immigrationlawyers-london.com/blog/uk-...,200,OK,UK Civil Partnership Visa Requirements and App...,UK Civil Partnership Visa Requirements and App...,Civil Partnership visa requirements,Document required for civil partnership visa a...,NaN,
689,https://immigrationlawyers-london.com/blog/uk-...,200,OK,UK Marriage Visa Requirements and Application,UK Marriage Visa Requirements and Application,What is UK Marriage Visa?,UK Marriage Visa Requirements,NaN,

In [ ]:
df_page.to_excel('Global mobility pages.xlsx',index=False)